dist: focal

before_install:
  - env TMPDIR=/tmp npm install -g phantomjs@1.9.20
  - env TMPDIR=/tmp npm install

addons:
  apt:
    packages:
    - ed
    - jsdoc-toolkit
    - libjs-bootstrap
    - libjs-jquery
    - libjs-jquery-ui
    - pax

script: >
    npm run build &&
    npm run build-tests &&
    npm run test &&
    npm run coverage &&
    ./scripts/post-coverage.sh &&
    ./scripts/weigh-in.sh
